<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>Tabela</title>
		<style>
			body
			{
				display: flex;
				justify-content: center;
				align-items: center;
			}
			#content
			{
				display: flex;
				align-items: center;
				flex-direction: row;
				gap: 10px;
			}
			#tables
			{
				display: flex;
				width: 30vw;
				flex-direction: row;
				flex-wrap: wrap;
				text-align: center;
			}
			h1
			{
				width: 30vw;
				border: solid black 4px;
				border-collapse: collapse;
				padding: 0px;
				margin: 0px;
			}
			.table
			{
				display: flex;
				flex-direction: row;
				justify-content: center;
				width: 30vw;
			}
			td
			{
				text-align: center;
				border: solid black 4px;
				width: 30vw;
				font-size: 1em;
			}
			.tableColumnShift
			{
				width: 10vw;
			}
			#clean
			{
				clear: both;
			}
			#area-print
			{
				float: left;
			}
			@media print
			{
				#tables
				{
					width: 90vw;
				}
				h1
				{
					width: 90vw;
				}
				.table
				{
					width: 90vw;
				}
				.tableColumnShift
				{
					width: 13vw;
				}
				td
				{
					font-size: 1.6em;
				}	
			}
		</style>
	</head>
	<body>
		<div id = content>
			<div id = "tables">

	
