<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>Tabela</title>
		<style>
			body
			{
				display: flex;
				justify-content: center;
			}
			#tables
			{
				display: flex;
				width: 80vw;
				flex-direction: row;
				flex-wrap: wrap;
				text-align: center;
			}
			h1
			{
				width: 80vw;
				border: solid black 4px;
				border-collapse: collapse;
				padding: 0px;
				margin: 0px;
			}
			.table
			{
				display: flex;
				flex-direction: row;
				justify-content: center;
				width: 80vw;
			}
			td
			{
				text-align: center;
				border: solid black 4px;
				width: 30vw;
				font-size: 1.4em;
			}
			.tableColumnShift
			{
				width: 10vw;
			}
			#clean
			{
				clear: both;
			}
		</style>
	</head>
	<body>
		<div id = "tables">

	
