<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>Tabela</title>
		<style>
			body
			{
				display: flex;
				justify-content: center;
			}
			#Table
			{
				display: flex;
				flex-direction: row;
				flex-wrap: wrap;
				justify-content: center;
			}
			#tableMorning
			{
				border-collapse: collapse;
				text-align: center;
				font-size: 1.3em;
				margin-left: 1vw;
			}
			td
			{
				border: solid black 4px;
				width: 25vw;
			}
			.tableColumnShift
			{
				width: 10vw;
			}
			#clean
			{
				clear: both;
			}
		</style>
	</head>
	<body>
		<div id = "Table">

	
