<label  class = "form__label" for = "shiftSelect">SELECIONAR TURNO</label>
<br>
<select class = "form__select" id = "shiftSelect" name = "cl_horarioInput">
	<option value = "06:00">06:00</option>
	<option value = "07:00">07:00</option>
	<option value = "08:00">08:00</option>
	<option value = "09:00">09:00</option>
	<option value = "10:00">10:00</option>
	<option value = "11:00">11:00</option>
	<option value = "12:00">12:00</option>
	<option value = "13:00">13:00</option>
	<option value = "14:00">14:00</option>
</select>
<br>