	<body id = "areaContent">
		<div id = "areaOfProject">
			<header id = "areaHeader">
				<ul id = " headerMenu" type = "none">
					<li><a class = "headerMenu__a" href = "/operador">OPERADOR</a></li>
					<li><a class = "headerMenu__a" href = "/empacotador">EMPACOTADOR</a></li>
					<li><a class = "headerMenu__a" href = "/carrinho">CARRINHOS</a></li>
					<li><a class = "headerMenu__a" href = "/tabela">TABELA</a></li>
				</ul>
			</header>