<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">
	<style>
		*
		{
			padding: 0;
			margin: 0;
			font-family: roboto;
		}
		#areaContent
		{
			height: 100vh;
			display: flex;
			flex-direction: column;
			justify-content: center;
			align-items: center;
		}
		#areaOfProject
		{
			display: flex;
			flex-direction: column;
			align-items: center;
			text-align: center;
			width: 40vw;
			gap: 0;
			border: solid 0.8vw black;
			background-color:#fc6f03;
		}
		#areaHeader
		{
			display: flex;
			justify-content: center;
			background-color: black;
			width: 40vw;
			border: 1px solid black;
			flex-wrap: wrap;
			font-size: 1.2em;
		}
		li
		{
			float: left;
		}
		.headerMenu__a
		{
			display: block;
			text-decoration: none;
			color: white;
			padding: 1.2vw;
		}
		.headerMenu__a:hover
		{
			background-color: white;
			border-radius: 1vw;
			color: black;
		}
		#areaForm
		{
			padding: 1vw;
		}
		.form__label,
		.form__select,
		.form__input,
		.form__button
		{
			margin: 1vw 0vw;
			width: 30vw;
			height: 6vh;
			font-size:1.6em;
			font-weight: 500;
			text-align: center;
		}
		.form__button
		{
			margin: 0.1vw 0vw;
			background-color: white;
			cursor: pointer;
			border: 0.2vw solid black;
		}
		.form__button:hover
		{
			background-color:#fc6f03;
		}
	</style>
	<title>teste</title>
</head>
