<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">
	<style>
		*
		{
			padding: 0;
			margin: 0;
			font-family: roboto;
			font-size: 1.04em;
		}
		#areaContent
		{
			height: 100vh;
			display: flex;
			justify-content: center;
			align-items: center;
		}
		#areaHeader
		{
			display: flex;
			justify-content: center;
			width: 41vw;
			background-color: black;
			flex-wrap: wrap;

		}
		#headerMenu
		{
		}
		li
		{
			float: left;
		}
		.headerMenu__a
		{
			display: block;
			text-decoration: none;
			color: white;
			padding: 1vw;
		}
		.headerMenu__a:hover
		{
			background-color: white;
			color: black;
		}
		#areaOfProject
		{
			display: flex;
			flex-direction: column;
			align-items: center;
			text-align: center;
			width: 40vw;
			border: solid 1vw black;
			background-color:#fc6f03;
		}
	</style>
	<title>teste</title>
</head>
